name: Java CI - Lemminx Liberty

on:
  push:
    branches:
      - main
      - appscan
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: maven
      - name: Build with Maven
        working-directory: ./lemminx-liberty
        run: mvn -B package --file pom.xml
      - name: HCL AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1
        with:
          asoc_key: ${{secrets.ASOC_KEY_ID}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
